### ISSUE TITLE
Feature Request: Ability to exclude file paths

### ISSUE THREAD

**Issue by ambernormand** [OWASP/SEDATED#14]
For example:
If we'd like to exclude anything within the `src/test` directory

This would be a cool feature that could help reduce the amount of false positive users face

**Comment by sclouts** [comment]
@ambernormand This is something @denniskennedy and I have previously considered many times and here is where we keep landing. If **SEDATED®** allowed for excluding something, there is always the chance that:

1. That directory eventually ends up (unintentionally/intentionally) containing a real credential. Simple example, a developer puts a real credential into their test case. 

2. That excluded folder could be a regularly used folder for source code (or whatever) in another language and now we've essentially excluded checking real code in that other language.

3. If a dev becomes a bad actor (unfortunately) they could exploit the use of this excluded folder and use it to store real creds.

Because of these reasons, and the real potential for these scenarios, we've pushed back on the idea of allowing to exclude anything and instead we are emphasizing the "whitelisting process" that we've created for these exact reasons. So for example:

If a developer commits something into "src/test" and they name the variable as such that we flag it, then **SEDATED®** blocks it, and the responsibility would be on the developer to raise a "false positive" request into the [commit whitelist file](https://github.com/OWASP/SEDATED/blob/master/config/whitelists/commit_whitelist.txt.example). This gives the security team the ability to manually review the code, confirm that the credential is not real, and then allow the push. But if the cred is real, then **SEDATED®** did it's job by blocking it, and the security team doesn't approve the whitelist request. 

I believe that this human intervention, for reviewing, is needed from time to time and is inevitable. Now, depending on the size of your company, maybe it's small enough that you feel confident the dev's are always complying with the do's and don'ts and that they wouldn't intentionally commit creds into the "excluded folder" but this still leaves everyone at risk for the "unintentional". I've seen it too many times where devs will do "git add --all" and just send everything without really reviewing, or they're working so fast that they make mistakes and copy and paste files (or lines code) into places they shouldn't be... I believe we need to protect ourselves from both intentional and unintentional. 

Now keep in mind, **SEDATED®** is setup (and we are continually evolving the regexes and will publish more updates soon) to recognize environment variable injection. With that said, src/test files can leverage environment variable injection and **SEDATED®** will not flag these (under most circumstances). This is the best option across the board whether it's the src/test folder, src folder, or any other file/folder.

So this is the convo Dennis and I have had many times around this issue and why we keep landing on "not adding exclude functionality". However, we do welcome your thoughts on this one as well as maybe you have other things we aren't considering or a different perspective or maybe some solutions to address the above concerns so please do feel free to share your thoughts!

**Comment by ambernormand** [comment]
Thanks for the update and I definitely understand the value of not excluding since it's valid that even within tests there may be true secrets that should be blocked. I can close this and it'll be here to refer back to!
