### ISSUE TITLE
Why is regexes.json in that format?

### ISSUE THREAD

**Issue by Asuza** [OWASP/SEDATED#20]
I've been tinkering with SEDATED and it looks like the _regexes.json_ file is not read by a JSON parser at all. I was curious what the reasoning for that was. Are there any plans to change the file to a format that does **not** require escaping quotes?

**Comment by sclouts** [comment]
@Asuza This is actually something we went back and forth on. Originally the plan was to use JQ to parse the json but there was the possibility of compatibility issues across the different platforms **SEDATED®** would be used on and so we decided against that for highest cross platform compatibility reasons, however, we still kept the format as JSON. 

I believe we performance tested parsing json (as-is the way we are now) vs just plain text file and the difference was trivial, however, dealing with escaping the quotes as we've updated regexes has certainty been annoying for us at times.

The main reason we left it in JSON format though is for a future upgrade currently on the to-do list. Specifically, we want the regexes to have the ability to be "file extension" specific. For a given regex, we want to be able to whitelist or blacklist what file extensions that regex gets applied to. By having this file in json format it can be highly configurable in this way simply because of what JSON format allows for. 

We are certainly open to any ideas or improvements you may have in mind for this that would help us accomplish what I mentioned above. If you have any ideas let us know, and/or if you end up testing out some code and want to raise a pull request that would certainty be appreciated! 

Happy coding ;-)

**Comment by Asuza** [comment]
I researched various existing data formats and couldn't find a clear winner for storing regular expressions, and many of them required additional parsers to actually use, so I ended up trying [TSV](https://en.wikipedia.org/wiki/Tab-separated_values).

The _regexes.tsv_ file would look like this:
```
Name	Expression
Filename	^(?:\+\+\+[[:space:]]b/)
Private_Key	[-]{5}BEGIN[[:space:]](?:[DR]SA|OPENSSH|EC|PGP)[[:space:]]PRIVATE[[:space:]]KEY(?:[[:space:]]BLOCK)?[-]{5}
AWS_Key	[[:space:]'\"=]A[KS]IA[0-9A-Z]{16}[[:space:]'\"]
AWS_Key_line_end	[[:space:]=]A[KS]IA[0-9A-Z]{16}$
Slack_token	xox[pboa]-[0-9]{11,12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32}
Basic_Auth	Authorization:[[:space:]]Basic[[:space:]](?:[a-zA-Z0-9\+/]{4})*(?:[a-zA-Z0-9\+/]{3}=|[a-zA-Z0-9\+/]{2}==)?(?:$|[[:space:];'\"])
.npmrc_auth	(?i)^\+[[:space:]]{0,20}\_auth[[:space:]]{0,20}=
Connection_String	[0-9a-z-]{3,30}(?<!mailto|sip):[a-z0-9!$)(=<>%#*&_^-]{6,45}@[0-9a-z-.]{1,50}(?:[[:space:];'\",:]|$)
JDBC_Connection_Creds	jdbc:oracle:thin:[0-9a-z-]{3,30}/[a-z0-9!?$)%@#*&_^-]+@
Keys	(?:(?:a(?:ws|ccess|p(?:i|p(?:lication)?)))|private|se(?:nsitive|cret))[[:space:]_-]?key[[:space:]]{1,20}[=:]{1,2}[[:space:]]{0,20}['\"]?(?=[a-z0-9!?$)=<\/>%@#*&{}_^-]{0,1200}[^[:space:]a-z;'\",\/.(_-][a-z0-9!?$)=<\/>%@#*&{}_^-]{0,1200})(?![$][a-z_-]{1,60}[[:space:];'\",])(?![#$]?{[^'\"]{1,60}})[a-z0-9!?$)=<\/>%@#*&{}_^-]{8,1200}(?:[[:space:];'\",]|$)
Keys_no_space	(?:(?:a(?:ws|ccess|p(?:i|p(?:lication)?)))|private|se(?:nsitive|cret))[[:space:]_-]?key[=:]{1,2}[[:space:]]{0,20}['\"]?(?=[a-z0-9!?$)=<\/>%@#*&{}_^-]{0,1200}[^[:space:]a-z;'\",\/.(_-][a-z0-9!?$)=<\/>%@#*&{}_^-]{0,1200})(?![$][a-z_-]{1,60}[[:space:];'\",])(?![#$]?{[^'\"]{1,60}})[a-z0-9!?$)=<\/>%@#*&{}_^-]{8,1200}(?:[[:space:];'\",]|$)
Password_Generic_with_quotes	(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret)['\"]?[[:space:]]{0,20}[=:]{1,3}[[:space:]]{0,20}[@]?['\"](?=[a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45}[^[:space:]a-z;'\",\/.(_-][a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45})(?![$][a-z_-]{1,45}[[:space:];'\",])(?![#$]?{[^'\"]{1,60}})[a-z0-9!?$)=<\/>%@#*&{}_^-]{6,45}['\"]
Password_equal_no_quotes	(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret)[[:space:]]{0,20}[=][[:space:]]{0,20}(?=[a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45}[^[:space:]a-z;'\",\/.(_-][a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45})(?![$#]?{[^[:space:];'\",]{1,60}})(?![$][a-z_-]{1,45}(?:(?:</)|[[:space:];'\",]|$))[a-z0-9!?$)=<\/>%@#*&{}_^-]{6,45}(?:(?:</)|[[:space:];'\",]|$)
Password_value	(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret).{0,10}value[=]['\"](?=[a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45}[^[:space:]a-z;'\",\/.(_-][a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45})(?![$][a-z_-]{1,45}[[:space:];'\",])(?![#$]?{[^'\"]{1,60}})[a-z0-9!?$)=<\/>%@#*&{}_^-]{6,45}['\"]
Password_primary	(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret)[[:space:]]primary[=]['\"](?=[a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45}[^[:space:]a-z;'\",\/.(_-][a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45})(?![$][a-z_-]{1,45}[[:space:];'\",])(?![#$]?{[^'\"]{1,60}})[a-z0-9!?$)=<\/>%@#*&{}_^-]{6,45}['\"]
Password_set	(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret)[(]['\"](?=[a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45}[^[:space:]a-z;'\",\/.(_-][a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45})(?![$][a-z_-]{1,45}[[:space:];'\",])(?![#$]?{[^'\"]{1,60}})[a-z0-9!?$)=<\/>%@#*&{}_^-]{6,45}['\"][)][;]
Password_admin	(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret)['\"]?[[:space:]]{0,20}[=:]{1,3}[[:space:]]{0,20}['\"]?admin[[:space:];'\",]
Password_String	(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret)[[:space:]]{0,20}[:]{1,3}[[:space:]]{1,20}string[[:space:]]{1,20}['\"](?=[a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45}[^[:space:]a-z;'\",\/.(_-][a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45})(?![$][a-z_-]{1,45}[[:space:];'\",])(?![#$]?{[^'\"]{1,60}})[a-z0-9!?$)=<\/>%@#*&{}_^-]{6,45}['\"]
Password_XML	<(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret)>(?![$#]{.{1,100}}</(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret)>)(?!%%.{1,100}%%</(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret)>).{5,1200}</(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret)>
Password_colon_no_quotes	(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret)[[:space:]]{0,20}(?!:=):[[:space:]]{0,20}(?=[a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45}[^[:space:]a-z;'\",\/.)(_-][a-z0-9!?$)=<\/>%@#*&{}_^-]{0,45})(?![$#]?{[^[:space:],;]{1,60}})(?![$][a-z_-]{1,45}(?:[[:space:],;]|$))[a-z0-9!?$)=<\/>%@#*&{}_^-]{6,45}(?:[[:space:],;]|$)
GitHub_Token	github.{0,20}['\"][a-z0-9]{35,40}['\"]
Facebook_Token	facebook.{0,30}['\"][0-9a-f]{32,255}['\"]
Twitter_Token	twitter.{0,30}['\"][a-z0-9]{35,44}['\"]
Heroku_Key	heroku.{0,30}[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}
```
If this format is acceptable, I can create a PR that properly uses it. I have it working locally right now.

It's easy to add more columns as needed to add a way to limit which types of files the regex would apply to.

**Comment by Asuza** [comment]
@SimeonCloutier, thoughts on this solution?

**Comment by sclouts** [comment]
@Asuza I was going to discuss this one with @denniskennedy last Friday but we've had our hands full preparing for a **SEDATED®** presentation. Him and I should be able to discuss though today or tomorrow and get back to you. Question for you though about this one, can you post an example of what the format would look like if we were to specify 1 to many file extensions that the regex is applicable to? I'd like to see what you were thinking for that scenario.

**Comment by Asuza** [comment]
@SimeonCloutier I would consider that a separate task entirely, though if the file extensions were added to the same file, it might look something like:
```
Name	Expression	Filter
Filename	^(?:\+\+\+[[:space:]]b/)	*.pl,*.php
Private_Key	[-]{5}BEGIN[[:space:]](?:[DR]SA|OPENSSH|EC|PGP)[[:space:]]PRIVATE[[:space:]]KEY(?:[[:space:]]BLOCK)?[-]{5}	*
AWS_Key	[[:space:]'\"=]A[KS]IA[0-9A-Z]{16}[[:space:]'\"]	*.yaml
```
As long as the file filter uses regex or something similar, it would allow a lot of flexibility in choosing or excluding specific files.

**Comment by sclouts** [comment]
@Asuza  Dennis and I took some time and really talked through this change. As we looked into it, we wanted to consider a future enhancement that is on on our radar which is allowing for file extension specific regexes. 

With that in mind, and because of the complexity of the regexes we keep landing on having to quote the regexes. If we were to use a delimited file then it is more than likely that now, or in the future, the delimited value (whether CSV, TSV, etc..) will likely end up in a regex somewheres at some point and therefore and would break the parsing of the file obviously. This is the reason we keep circling back to the original requirement of needing to put the regexes into a quoted string. 

Now, the regexes could be in a quoted string inside JSON, TSV, CSV, etc.... but a concern with the TSV in particular is that there are different tab characters depending on your IDE and/or operating system. For instance, some OS/IDE's may use  ASCII 11 for a tab, and other IDE's/OS's may use 3 spaces (ASCII 40 x 3) for a tab so that could lead to issues that would break the parsing and create bugs that are very difficult to troubleshoot.

If you have any alternative solutions for getting around these potential issues let us know, but for making this as compatible as possible across the platforms I don't this going to work at the scale we need it to. 

Thanks for your contributions and please let us know if you have further ideas/thoughts on this!

**Comment by Asuza** [comment]
@SimeonCloutier, thank you for your detailed response. I believed the TSV format could assist with the problem of quoted regex because a literal tab character in a regex seemed like a rarity to me, considering that tabs can be searched via the `\t` character class. Though, the whole issue can be avoided by changing the order of the columns, as shown here:

```
Name	Filter	Expression
Filename	*.pl,*.php	^(?:\+\+\+[[:space:]]b/)
Private_Key	*	[-]{5}BEGIN[[:space:]](?:[DR]SA|OPENSSH|EC|PGP)[[:space:]]PRIVATE[[:space:]]KEY(?:[[:space:]]BLOCK)?[-]{5}
AWS_Key	*.yaml	[[:space:]'\"=]A[KS]IA[0-9A-Z]{16}[[:space:]'\"]
```
In the example, everything beyond the second literal tab is regex, without question. Additionally, SEDATED itself could have a check to ensure the config file contains literal tabs. That way, if someone's editor converts the tabs to spaces unintentionally, a warning would appear to explain the issue.

The OS/IDE tab issue is a little more problematic. With clear documentation (perhaps in the _regexes.tsv_ file itself), would it be an issue? I had problems figuring out how to use literal tabs in my own editor as I was trying to figure all of this out. However, that was a one-time hurdle and I got to learn something new. It was orders of magnitude easier than constantly escaping and unescaping regexes to match strings I was trying to catch as I moved them between the config file and regex tools.

I'd like to believe most people would prefer an occasional tab inconvenience to dealing with escaped quotes, but I can't say for sure! What are your feelings on it?

**Comment by Asuza** [comment]
@SimeonCloutier and/or @denniskennedy, let me know what you think when you get a few minutes. I don't want to forget about it.

**Comment by d3jk** [comment]
The problem you stated with your IDE is the exact problem we have concerns about. Some IDEs interpret tab characters as 2 spaces, some 4 spaces, some literal tabs... this is not an easy issue to debug as it deals only in whitespace. While I would agree escaping double quotes is inconvenient, it is much easier to debug, less frustrating, and more widely understood than whitespace issues. We would like to fix the escaped quotes issues, however we don't feel this is the better solution we need as it introduces a new, more obscure problem while solving the other, better known problem. Definitely appreciate the brainstorming on this with you and if you happen to come up with a solution that doesn't have this issue, we would love to hear about it 🙂  Are you good to close this issue, at least for now?
